"""empty message

Revision ID: 11765c55d672
Revises: d98d30fe16c8
Create Date: 2025-03-17 01:45:28.170349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11765c55d672'
down_revision = 'd98d30fe16c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipes_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_recipes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_recipes_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
